
name: GithubAction Tests

on:
  push:
    branches: master

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo 'Hello Test'
        echo ${{ secrets.MYSECRETNAME }}
        sh ./my_script_test.sh
