
name: GithubAction Tests

on:
  push:
    branches: develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: test
      run: |
        echo 'Hello Test from develop'
        echo ${{ secrets.MYSECRETNAME }}
        sh ./my_script_test.sh
        
  test_python:
    runs-on: ubuntu-latest
    
    steps:
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: Check python version
      run: python --version
